### PR TITLE
Minor edits for clarity

### PR DESCRIPTION
**Pull request by nicklucius**
* Makes a few changes intended to help readability
* Updates `dev` branch so it is not behind by one commit
* Fixes some references to figures and sections

### CODE REVIEW

**Comment by nicklucius** [comment]
@tomschenkjr - there is still one issue I didn't address: there's a reference to "Table S2" in the last paragraph [here](https://github.com/Chicago/predicting-e-coli-concentrations/blob/master/predicting-e-coli-concentrations.Rmd#results-and-discussion), which was the confusion matrix. That's no longer a table, so I wondered if you have thoughts on how to handle that.

**Comment by tomschenkjr** [comment]
Ah, I thought I caught all of them. Let’s remove references to supplemental tables from the body.

**Comment by nicklucius** [comment]
I removed the reference to Table S2. I also have noticed that the confusion matrix is not generating with the supplementary materials at the end. I can't seem to figure out what is happening. @tomschenkjr - could you take a look?

**Comment by tomschenkjr** [comment]
Will do.

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Pull request merged**
